version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - springboot-mongo-network

  sb-user:
    image: sb-user
    build:
      context: ./sb-user
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7072:7072"
    networks:
      - springboot-mongo-network

  sb-blog-info:
    image: sb-blog-info
    build:
      context: ./sb-blog-info
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7070:7070"
    networks:
      - springboot-mongo-network

  sb-blog-business:
    image: sb-blog-business
    build:
      context: ./sb-blog-business
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7071:7071"
    networks:
      - springboot-mongo-network

  sb-blog-comments:
    image: sb-blog-comments
    build:
      context: ./sb-blog-comments
      dockerfile: Dockerfile
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/my_first_spring_project
    depends_on:
      - mongo
    ports:
      - "7075:7075"
    networks:
      - springboot-mongo-network

  api-gateway:
    image: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    depends_on:
      - sb-user
      - sb-blog-info
      - sb-blog-business
      - sb-blog-comments
    ports:
      - "8084:8084"
    networks:
      - springboot-mongo-network

  service-discovery:
    image: service-discovery
    build:
      context: ./service-discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - springboot-mongo-network

volumes:
  mongo-data:

networks:
  springboot-mongo-network:
