spring:
  application:
    name: service-discovery

  cloud:
    gateway:
      discovery:
        locator:
          enabled:true


server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false