# This file is now fully self-contained.
# It creates its own network called 'keycloak-net'.

services:
  keycloak-db:
    image: postgres:13-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password # CHANGE FOR PRODUCTION!
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-net # Connects to the private network defined below
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080" # Exposes Keycloak to your host machine
    depends_on:
      keycloak-db:
        condition: service_healthy
    networks:
      - keycloak-net # Connects to the private network defined below

volumes:
  keycloak-db-data:

# This section DEFINES and CREATES the network for this stack.
# It is NOT external.
networks:
  keycloak-net:
    driver: bridge