version: '3.8'

services:
  freeradius:
    image: freeradius/freeradius-server
    container_name: freeradius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./freeradius/clients.conf:/etc/freeradius/3.0/clients.conf
      - ./freeradius/users:/etc/freeradius/3.0/users
    restart: unless-stopped
